### PR TITLE
Laravel 10.x Support

### LINKED ISSUE #145: is there gonna be Laravel 10.x support?
@topclaudy is there gonna be Laravel 10.x support?

### PR DESCRIPTION
**Pull request by erikn69**
Closes #145

### CODE REVIEW

**Comment by erikn69** [comment]
@topclaudy suggestions? ideas? reviews?

**Comment by topclaudy** [comment]
Thanks @erikn69  I'll take a look next week.

**Comment by parallels999** [comment]
@topclaudy hi, LGTM 
#145

**Comment by topclaudy** [comment]
Thanks @erikn69

**Comment by parallels999** [comment]
@topclaudy please make a release for packagist

**Pull request merged**
