### PR TITLE
extends from HasOne / HasMany instead of HasOneOrMany

### PR DESCRIPTION
**Pull request by lordofthebrain**
This is important, when you working with interfaces which use HasOne / HasMany as return type.

### CODE REVIEW

**Comment by lordofthebrain** [comment]
I've change your abstract class to a trait and use this in HasOne und HasMany
Tests green :)

**Comment by topclaudy** [comment]
After the merge I got this error "Class Awobaz\Compoships\Database\Eloquent\Relations\HasMany cannot extend from trait Awobaz\Compoships\Database\Eloquent\Relations\HasOneOrMany"

**Comment by lordofthebrain** [comment]
Where do you get that error? In the tests?

**Comment by topclaudy** [comment]
Yep

**Pull request merged**
